/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Point;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author Kylo55
 */
public class ElevatorForm extends javax.swing.JFrame {

  /**
   * Creates new form ElevatorForm
   */
  public ElevatorForm () {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    elevatorLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    elevatorLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/winda.jpg"))); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(162, 162, 162)
        .addComponent(elevatorLabel)
        .addContainerGap(188, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(464, Short.MAX_VALUE)
        .addComponent(elevatorLabel)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main (String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ElevatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ElevatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ElevatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ElevatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      new ElevatorForm().setVisible(true);
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel elevatorLabel;
  // End of variables declaration//GEN-END:variables

  private boolean end = false;
  private final List<Integer> floors = Arrays.asList(464, 414, 364, 314, 264, 214, 164, 114, 64, 14);

  void startMoving (int floor, int mass) {
    final Elevator elevator = new Elevator(464, floors.get(floor-1), mass, 1);
    Thread animationThread = new Thread(() -> {
      while (!end) { //450 jednostek ruchu
        final Point location = elevatorLabel.getLocation(); //start y = 464
        if (location.getY() < floors.get(floor - 1)) {
          end = true;
        }
        location.setLocation(location.getX(), location.getY() - elevator.calculateMovement());
        elevatorLabel.setLocation(location);
        repaint();
        try {
          Thread.sleep(10);
        } catch (InterruptedException ex) {
          System.out.println("Przerwanie" + ex);
        }
      }
    });
    animationThread.start();
  }
}
