/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Point;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author Kylo55
 */
public class ElevatorForm extends javax.swing.JFrame {

  private MainWindow mainWindow;

  /**
   * Creates new form ElevatorForm
   */
  public ElevatorForm () {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    elevatorLabel = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    elevatorLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/winda.jpg"))); // NOI18N

    jLabel1.setText("Pietro 1");

    jLabel2.setText("Pietro 2");

    jLabel3.setText("Pietro 3");

    jLabel4.setText("Pietro 4");

    jLabel5.setText("Pietro 5");

    jLabel6.setText("Pietro 6");

    jLabel7.setText("Pietro 7");

    jLabel8.setText("Pietro 8");

    jLabel9.setText("Pietro 9");

    jLabel10.setText("Pietro 10");
    jLabel10.setLocation(jLabel1.getLocation().x, 14);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(48, 48, 48)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel10)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel8)
            .addComponent(jLabel9)
            .addComponent(jLabel7)
            .addComponent(jLabel6)
            .addComponent(jLabel5)
            .addComponent(jLabel4)
            .addComponent(jLabel3)
            .addComponent(jLabel2)
            .addComponent(jLabel1)))
        .addGap(74, 74, 74)
        .addComponent(elevatorLabel)
        .addContainerGap(185, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(87, Short.MAX_VALUE)
        .addComponent(jLabel10)
        .addGap(34, 34, 34)
        .addComponent(jLabel9)
        .addGap(34, 34, 34)
        .addComponent(jLabel8)
        .addGap(34, 34, 34)
        .addComponent(jLabel7)
        .addGap(34, 34, 34)
        .addComponent(jLabel6)
        .addGap(34, 34, 34)
        .addComponent(jLabel5)
        .addGap(34, 34, 34)
        .addComponent(jLabel4)
        .addGap(34, 34, 34)
        .addComponent(jLabel3)
        .addGap(28, 28, 28)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addGap(34, 34, 34)
            .addComponent(jLabel1))
          .addComponent(elevatorLabel))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main (String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ElevatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ElevatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ElevatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ElevatorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      new ElevatorForm().setVisible(true);
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel elevatorLabel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  // End of variables declaration//GEN-END:variables

  private boolean end = false;
  private final List<Integer> floors = Arrays.asList(464, 414, 364, 314, 264, 214, 164, 114, 64, 14);

  void startMoving (int floor, int mass) {
    final Elevator elevator = new Elevator(464, floors.get(floor - 1), mass, 1);
    Thread animationThread = new Thread(() -> {
      while (!end) { //450 jednostek ruchu
        final Point location = elevatorLabel.getLocation(); //start y = 464
        if (location.getY() < floors.get(floor - 1)) {
          end = true;
        }
        final double calculateMovement = elevator.calculateMovement();
        if(calculateMovement == 0) end = true;
        location.setLocation(location.getX(), location.getY() - calculateMovement);
        elevatorLabel.setLocation(location);
        mainWindow.updateLabels(elevator);
        repaint();
        try {
          Thread.sleep(50);
        } catch (InterruptedException ex) {
          System.out.println("Przerwanie" + ex);
        }
      }
    });
    animationThread.start();
  }

  void setMainWindow (MainWindow aThis) {
    this.mainWindow = aThis;
  }
}
